### ISSUE TITLE
你的测试里面明明spring垫底，却说dubbo， 不地道

### ISSUE THREAD

**Issue by longdafeng** [hank-whu/rpc-benchmark#4]
拜托，不要拿dubbo做噱头

**Comment by hank-whu** [comment]
@longdafeng 
哈哈，吸睛才能有曝光，抱歉给你造成困扰。
不过在 listUser 这个项目上 dubbo 确实垫底了，单链接+老旧的 hession2 让它在这项上吃亏了。

**Comment by longdafeng** [comment]
其实行业内有专业的 rpc 性能测试， 你这种benchmark只能说玩一玩

公平来说， 你这套框架还是有一些意义， 让入门的人快速上手或者知道有这么多框架。

关于垫底
（1）即使是listuser， 在你这个测试里面， dubbo 只是很靠后， 也不是垫底。 另外这么多测试，你偏挑一个来说事，也是不地道。
（2）另外，你自己都说了 “利益相关: 本测试用例作者同时为 turbo, undertow-async 的作者”， 我只能说 又是裁判又是运动员 
（3）在一般程序员心中， spring的rpc 是比较差的， 但是大家都能接受，并且不会因为他这点差而不用他， 因为这不是他最擅长， 另外spring能帮助java程序员太多 


另外，后面我也不公开回了， 感觉你只是吸引更多的人来用你的turbo/undertow-async

不过我们可以私聊， 我邮箱 hustjackie@gmail.com

**Comment by hank-whu** [comment]
我这个其实是参考了 [techempower-benchmarks](https://www.techempower.com/benchmarks/) 我一直挺欣赏这种规则公开透明的测试方法。
排除掉 turbo 的结果，这个测试也是具有一定的参考价值的。
确实不知道还存在专门做 rpc 性能测试的标准，如果你这里有的话请发出来学习一下。
