### ISSUE TITLE
感谢对Jupiter的benchmark, 让我学到了不少

### ISSUE THREAD

**Issue by fengjiachun** [hank-whu/rpc-benchmark#5]
@hank-whu 
首先非常感谢rpc-benchmark这个项目包含了Jupiter, 让我了解到了jupiter的一些不足之处, 我粗略读了下turbo-rpc的代码和设计思路
有一处我觉得是非常大亮点:
   1. 在反序列化的时候通常的做法是ByteBuf转为bytes[] 再进行反序列化, 作者的turbo-rpc巧妙的避免了这次memory copy, 唯一遗憾的这导致了Serializer与Netty#ByteBuf的耦合(不过我相信这个是可以解决的)
   2. 序列化的时候同理
节省了这两次memory copy, 对框架整体吞吐的提升应该是比较显著的, jupiter后面也希望借鉴这个优化思路
再次感谢, 学习到了新思路新知识

**Comment by hank-whu** [comment]
不客气，互相学习

**Comment by hank-whu** [comment]
我写了一篇文章，大概介绍了下 turbo 的技术原理，https://www.jianshu.com/p/7182b8751e75
